### ISSUE TITLE
Add usage instructions

### ISSUE THREAD

**Issue by jedesah** [scaladyno/scaladyno-plugin#1]

**Comment by VladUreche** [comment]
@jedesah, scaladyno doesn't have a maintainer atm, since @cedricbastin is busy with other things. Without proper support and engineering, I can't recommend anyone to use scaladyno on large code bases. :(

**Comment by jedesah** [comment]
Hmm, that's too bad. I would like to try it on a small project of mine. And who knows, I might fix a few things if it's not too much effort to get it to work on a small code base. I guess I can figure out how to publishLocal or something for testing, I have never used a compiler plugin that was not on maven central before.

**Comment by VladUreche** [comment]
@jedesah, I included some very basic setup instructions in the README file:

```
$ git clone https://github.com/scaladyno/scaladyno-plugin.git
$ cd scaladyno-plugin
$ sbt package
```

You should also have a local instalaltion of Scala 2.11.0 and the `SCALA_PATH` set to its `bin` directory. From the `scaladyno-plugin` directory you can run your local Scala 2.11 with the plugin enabled by running the `dy-scala` and `dy-scalac` scripts:

```
$ ./dy-scalac demo.scala 
demo.scala:10: warning: [suppressed error] not found: type NoSuchClass
      val x = new NoSuchClass
                  ^
one warning found
```

Let me know if you have any trouble setting it up on your machine.

**Comment by VladUreche** [comment]
If you're familiar with macros, it's not much harder to work on compiler plugins, you get the full API and you can tweak pretty much anything :)

**Comment by jedesah** [comment]
@VladUreche Thank you for taking the time to do this. I am fairly familiar with macros, so hopefully I should be able to find my way around.

**Comment by VladUreche** [comment]
Cool! If there are things you don't understand, just let me know and I will explain. There are 3 really good videos on the compiler internals: http://www.scala-lang.org/old/node/598 (they were shot before macros appeared, so packages may have changed, but the architecture is still the same)
